CREATE DATABASE RestauranteSamogi;

USE RestauranteSamogi;

CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY,
FNAMEC VARCHAR(100),
LNAMEC VARCHAR(100),
DIRECTION VARCHAR(100),
PHONE_NUMBER VARCHAR(100)
);


CREATE TABLE SIZES(
SIZE_ID INT PRIMARY KEY,
DESCRIPTION VARCHAR(100)
);



CREATE TABLE PRICES(
PRICE_ID INT PRIMARY KEY,
DESCRIPTION VARCHAR(100)
);


CREATE TABLE CATEGORIES(
CATEGORY_ID INT PRIMARY KEY,
DESCRIPTION VARCHAR(100)
);



CREATE TABLE DEALERS(
DEALER_ID INT PRIMARY KEY,
DESCRIPTION VARCHAR(100)
);

CREATE TABLE PRODUCTS(
PRODUCT_ID INT,
NAMEP VARCHAR(100),
SIZE_ID INT,
PRICE_ID INT,
CATEGORY_ID INT,
CONSTRAINT PK_PRODUCT_ID PRIMARY KEY(PRODUCT_ID),
CONSTRAINT FK_PRICE_ID FOREIGN KEY (PRICE_ID) REFERENCES PRICES(PRICE_ID),
CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
CONSTRAINT FK_SIZE_ID FOREIGN KEY (SIZE_ID) REFERENCES SIZES(SIZE_ID)
);


CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT,
FNAMEE VARCHAR(100),
LNAMEE VARCHAR(100),
DEALER_ID INT,
CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY(EMPLOYEE_ID),
CONSTRAINT FK_DEALER_ID FOREIGN KEY (DEALER_ID) REFERENCES DEALERS(DEALER_ID)
);



CREATE TABLE ORDERS(
ORDER_ID INT,
AMOUNT INT,
CUSTOMER_ID INT,
PRODUCT_ID INT,
EMPLOYEE_ID INT,
ORDER_DATE DATE,
CONSTRAINT PK_ORDER_ID PRIMARY KEY(ORDER_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
);



