CREATE DATABASE DW_RestauranteSamogi;
use  DW_RestauranteSamogi
USE MASTER

CREATE TABLE Dim_Employees(
Employee_ID int PRIMARY KEY,
employee_FullName VARCHAR(100)
);


CREATE TABLE Dim_Customers(
CUSTOMER_ID int PRIMARY KEY,
CUSTOMER_FULLNAME VARCHAR(100)
);


CREATE TABLE Dim_Products(
PRODUCT_ID int PRIMARY KEY,
PRODUCT_NAME VARCHAR(100),
PRODUCT_SIZE  VARCHAR(100),
PRODUCT_PRICE FLOAT,
PRODUCT_CATEGORY VARCHAR(100)
);



CREATE TABLE Dim_TIME(
TIME_ID DATE PRIMARY KEY,
MONTHO INT, 
trimester INT,
semester INT,
week_day VARCHAR(20)
);



CREATE TABLE Hechos_Orders_Sales(
HECHO_ID int IDENTITY(1,1) PRIMARY KEY,
EMPLOYEE_ID int,
CUSTOMER_ID int,
PRODUCT_ID int,
TIME_ID DATE,
TOTAL_AMOUNT FLOAT,
QUANTITY_CLIENTS int,
QUANTITY_SALE_PRODUCTS int,
CONSTRAINT FK_employee_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES Dim_Employees(Employee_ID),
CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES Dim_Customers(CUSTOMER_ID),
CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES Dim_Products(PRODUCT_ID),
CONSTRAINT FK_TIME_ID FOREIGN KEY (TIME_ID) REFERENCES Dim_TIME(TIME_ID)
);


